### ISSUE TITLE
build doesn't produce js files

### ISSUE THREAD

**Issue by mvayngrib** [tobysmith568/license-cop#142]
when i run `npm run build`, no JS files are created for some reason. I tried added the `--verbose` flag for `nx` and i see:
```
> nx run license-cop:build

Compiling with SWC for license-cop...
Successfully compiled: 29 files with swc (64.42ms)
```

but no JS files 😅

I'm probably doing something wrong, any idea what it might be? 🙏 . My env:
- macos
- node (tried 18.20.1, v20.10.0)

another symptom i'm not sure is related is that `npm run build` hangs forever:
```
> license-cop-monorepo@0.0.0 build
> npx nx run-many --target build --verbose


 NX   Running target build for 9 projects:

- e2e-isc-legacy-package
- e2e-no-license-package
- e2e-unlicensed-package
- e2e-uses-isc-package
- e2e-isc-package
- e2e-mit-package
- license-cop
- permissive
- website

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run e2e-isc-package:build

Compiling TypeScript files for project "e2e-isc-package"...
Done compiling TypeScript files for project "e2e-isc-package".

> nx run e2e-isc-legacy-package:build

Compiling TypeScript files for project "e2e-isc-legacy-package"...
Done compiling TypeScript files for project "e2e-isc-legacy-package".

> nx run license-cop:build

Compiling with SWC for license-cop...
Successfully compiled: 29 files with swc (56.23ms)

> nx run e2e-no-license-package:build

Compiling TypeScript files for project "e2e-no-license-package"...
Done compiling TypeScript files for project "e2e-no-license-package".

> nx run e2e-unlicensed-package:build

Compiling TypeScript files for project "e2e-unlicensed-package"...
Done compiling TypeScript files for project "e2e-unlicensed-package".

> nx run e2e-mit-package:build

Compiling TypeScript files for project "e2e-mit-package"...
Done compiling TypeScript files for project "e2e-mit-package".

> nx run e2e-uses-isc-package:build

Compiling TypeScript files for project "e2e-uses-isc-package"...
Done compiling TypeScript files for project "e2e-uses-isc-package".

> nx run website:build

(!) Experimental optimizeDeps.disabled and deps pre-bundling during build were removed in Vite 5.1.
    To disable the deps optimizer, set optimizeDeps.noDiscovery to true and optimizeDeps.include as undefined or empty.
    Please remove optimizeDeps.disabled from your config.
    
  
09:00:11 [WARN] [vite] (!) Experimental optimizeDeps.disabled and deps pre-bundling during build were removed in Vite 5.1.
    To disable the deps optimizer, set optimizeDeps.noDiscovery to true and optimizeDeps.include as undefined or empty.
    Please remove optimizeDeps.disabled from your config.
    
  
09:00:11 [build] output: "static"
09:00:11 [build] directory: /Users/mv/code/license-cop/dist/apps/website/
09:00:11 [build] Collecting build info...
09:00:11 [build] ✓ Completed in 30ms.
09:00:11 [build] Building static entrypoints...
09:00:12 [vite] ✓ built in 1.26s
09:00:12 [build] ✓ Completed in 1.28s.

 building client (vite) 
09:00:12 [vite] transforming...
09:00:12 [vite] ✓ 2 modules transformed.
09:00:12 [vite] rendering chunks...
09:00:12 [vite] ✓ built in 8ms

 generating static routes 
09:00:12 ▶ src/pages/index.astro
09:00:12   └─ /index.html (+6ms)
09:00:13 ▶ src/pages/third-party.astro
09:00:13   └─ /third-party.html (+810ms)
09:00:14 ▶ src/pages/permissive.mdx
09:00:14   └─ /permissive.html (+111ms)
09:00:14 ▶ src/pages/cookies.md
09:00:14   └─ /cookies.html (+2ms)
09:00:14 ▶ src/pages/privacy.md
09:00:14   └─ /privacy.html (+2ms)
09:00:14 ▶ src/pages/shield.md
09:00:14   └─ /shield.html (+2ms)
09:00:14 ▶ src/pages/terms.md
09:00:14   └─ /terms.html (+2ms)
09:00:14 ▶ src/pages/docs.md
09:00:14   └─ /docs.html (+1ms)
09:00:14 ▶ src/pages/404.astro
09:00:14   └─ /404.html (+4ms)
09:00:14 ✓ Completed in 1.30s.

@astrojs/sitemap: `sitemap-index.xml` created at `../../dist/apps/website`

astro-webmanifest: `manifest.webmanifest` is created.

astro-webmanifest: Webmanifest links are inserted into <head> section of generated pages (9 of 9).

09:00:14 [build] 9 page(s) built in 2.68s
09:00:14 [build] Complete!
```

when i interrupt it, it logs this:
```
^Cnode:internal/util:343
  throw new ERR_UNKNOWN_SIGNAL(signal);
  ^

TypeError [ERR_UNKNOWN_SIGNAL]: Unknown signal: 130
    at convertToValidSignal (node:internal/util:343:9)
    at ChildProcess.kill (node:internal/child_process:496:5)
    at process.processExitListener (/Users/mv/code/license-cop/node_modules/nx/src/executors/run-commands/run-commands.impl.js:201:62)
    at process.emit (node:events:526:35)
    at process.exit (node:internal/process/per_thread:193:15)
    at process.<anonymous> (/Users/mv/code/license-cop/node_modules/nx/src/tasks-runner/forked-process-task-runner.js:345:21)
    at process.emit (node:events:526:35) {
  code: 'ERR_UNKNOWN_SIGNAL'
}
```

**Comment by tobysmith568** [comment]
Happy you got to the end of this :)
